version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - npm install -g pnpm
      - pnpm install --frozen-lockfile
      # - |
      #   if [ -d node_modules ]; then
      #     echo "Using cached node_modules"
      #   else
      #     echo "Installing new dependencies"
      #     pnpm install --frozen-lockfile
      #   fi
  pre_build:
    commands:
      - echo $GITHUB_URL
      - yum install -y git
      - echo "Checking for changes in apps"
      - git config --global init.defaultBranch main
      - git init .
      - git branch -M main
      - git remote add origin $GITHUB_URL
      - git fetch origin main
      - git reset --hard origin/main
      - |
        CHANGED_DIRS=$(git diff --name-only HEAD~1 | grep -E 'apps/.*' | cut -d/ -f2 | sort -u)
        echo "Changed directories: $CHANGED_DIRS"
  build:
    commands:
      - |
        for dir in $CHANGED_DIRS; do
          case "$dir" in
            "_shell")
              echo "Building _shell app"
              pnpm --filter shell build
              ;;
            "health")
              echo "Building health app"
              pnpm --filter health build
              ;;
            "insurance")
              echo "Building insurance app"
              pnpm --filter insurance build
              ;;
            "mydata")
              echo "Building mydata app"
              pnpm --filter mydata build
              ;;
            *)
              echo "Unknown directory: $dir"
              ;;
          esac
        done
  post_build:
    commands:
      - |
        for dir in $CHANGED_DIRS; do
          case "$dir" in
            "_shell")
              echo "Syncing _shell app"
              aws s3 sync ./apps/_shell/dist/ s3://mfa-template-s3
              ;;
            "health")
              echo "Syncing health app"
              aws s3 sync ./apps/health/dist/ s3://mfa-template-s3/health --exclude "index.html"
              ;;
            "insurance")
              echo "Syncing insurance app"
              aws s3 sync ./apps/insurance/dist/ s3://mfa-template-s3/insurance --exclude "index.html"
              ;;
            "mydata")
              echo "Syncing mydata app"
              aws s3 sync ./apps/mydata/dist/ s3://mfa-template-s3/mydata --exclude "index.html"
              ;;
            *)
              echo "Unknown directory: $dir"
              ;;
          esac
        done
      - aws cloudfront create-invalidation --distribution-id E1RI9WI1EF5TV3 --paths '/*'
artifacts:
  files:
    - "**/*"
  base-directory: ./
# cache:
#   paths:
#     - "/node_modules/.pnpm/**/*"