version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - npm install -g pnpm
      - pnpm install
  pre_build:
    commands:
      - export TURBO_API=$TURBO_API
      - export TURBO_TEAM=$TURBO_TEAM
      - export TURBO_TOKEN=$TURBO_TOKEN
      - mkdir -p .turbo
      - |
        echo "{
          \"apiurl\": \"$TURBO_API\",
          \"teamslug\": \"$TURBO_TEAM\",
          \"token\": \"$TURBO_TOKEN\"
        }" > .turbo/config.json
      - cat .turbo/config.json
  build:
    commands:
      - set -e 
      - echo "Running turborepo build..."
      - pnpm build
  post_build:
    commands:
      - |
        echo "Running deploy script..."
        chmod +x ./deploy.sh

        aws s3 sync ./apps/_shell/dist/ s3://mfa-template-s3
        aws s3 sync ./apps/health/dist/ s3://mfa-template-s3/health --exclude "index.html"
        aws s3 sync ./apps/insurance/dist/ s3://mfa-template-s3/insurance --exclude "index.html"
        aws s3 sync ./apps/mydata/dist/ s3://mfa-template-s3/mydata --exclude "index.html"
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

        echo "Deployment complete!"
artifacts:
  files:
    - "apps/*/dist/**/*"
  base-directory: ./
cache:
  paths:
    - '.pnpm-store/**/*'
    - '.turbo/**/*'
