version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - npm install -g pnpm
  pre_build:
    commands:
      - echo $GITHUB_URL
      - yum install -y git  # Git 설치
      - pnpm i
      - echo "Checking for changes in apps"
      - git init
      - git config --global init.defaultBranch main  # 기본 브랜치를 main으로 설정
      - git branch -M main  # 현재 브랜치를 main으로 변경
      - git remote add origin $GITHUB_URL
      - git fetch origin main --depth=1
      - git reset --hard origin/main
      - |
        CHANGED_DIRS=$(git diff --name-only HEAD~1 | grep -E 'apps/.*' | cut -d/ -f2 | sort -u)
        echo "Changed directories: $CHANGED_DIRS"
  build:
    commands:
      # - pnpm build
      - |
        if echo "$CHANGED_DIRS" | grep -q "_shell"; then
          echo "Building _shell app"
          pnpm --filter shell build
        fi
        if echo "$CHANGED_DIRS" | grep -q "health"; then
          echo "Building health app"
          pnpm --filter health build
        fi
        if echo "$CHANGED_DIRS" | grep -q "insurance"; then
          echo "Building insurance app"
          pnpm --filter insurance build
        fi
        if echo "$CHANGED_DIRS" | grep -q "mydata"; then
          echo "Building mydata app"
          pnpm --filter mydata build
        fi
  post_build:
    commands:
      - rm -rf ./mfa-template-pipelin
      # - aws s3 sync ./apps/_shell/dist/ s3://mfa-template-s3
      # - aws s3 sync ./apps/health/dist/ s3://mfa-template-s3/health --exclude "index.html"
      # - aws s3 sync ./apps/insurance/dist/ s3://mfa-template-s3/insurance --exclude "index.html"
      # - aws s3 sync ./apps/mydata/dist/ s3://mfa-template-s3/mydata --exclude "index.html"
      - |
        if echo "$CHANGED_DIRS" | grep -q "_shell"; then
          aws s3 sync ./apps/_shell/dist/ s3://mfa-template-s3
        fi
        if echo "$CHANGED_DIRS" | grep -q "health"; then
          aws s3 sync ./apps/health/dist/ s3://mfa-template-s3/health --exclude "index.html"
        fi
        if echo "$CHANGED_DIRS" | grep -q "insurance"; then
          aws s3 sync ./apps/insurance/dist/ s3://mfa-template-s3/insurance --exclude "index.html"
        fi
        if echo "$CHANGED_DIRS" | grep -q "mydata"; then
          aws s3 sync ./apps/mydata/dist/ s3://mfa-template-s3/mydata --exclude "index.html"
        fi
      - aws cloudfront create-invalidation --distribution-id E1RI9WI1EF5TV3 --paths '/*'
artifacts:
  files:
    - "**/*"
  base-directory: ./
  

