version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - npm install -g pnpm
  pre_build:
    commands:
      - pnpm i
  build:
    commands:
      - pnpm build
  post_build:
    commands:
      - aws s3 sync ./apps/_shell/dist/ s3://mfa-template-s3 --exclude "mfa-template-pipelin/*"
      - aws s3 sync ./apps/health/dist/ s3://mfa-template-s3/health --exclude "mfa-template-pipelin/*" --exclude "index.html"
      - aws s3 sync ./apps/insurance/dist/ s3://mfa-template-s3/insurance --exclude "mfa-template-pipelin/*" --exclude "index.html"
      - aws s3 sync ./apps/mydata/dist/ s3://mfa-template-s3/mydata --exclude "mfa-template-pipelin/*" --exclude "index.html"
artifacts:
  files:
    - "**/*"
  base-directory: ./
  discard-paths: yes
  exclude-paths:
    - "mfa-template-pipelin/*"
