version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - npm install -g pnpm
  pre_build:
    commands:
      - pnpm i
      - echo "Checking for changes in apps"
      - |
        CHANGED_DIRS=$(git diff --name-only HEAD~1 | grep -E 'apps/.*' | cut -d/ -f2 | sort -u)
        echo "Changed directories: $CHANGED_DIRS"
  build:
    commands:
      - pnpm build
  post_build:
    commands:
      - rm -rf ./mfa-template-pipelin
      - aws s3 sync ./apps/_shell/dist/ s3://mfa-template-s3
      - aws s3 sync ./apps/health/dist/ s3://mfa-template-s3/health --exclude "index.html"
      - aws s3 sync ./apps/insurance/dist/ s3://mfa-template-s3/insurance --exclude "index.html"
      - aws s3 sync ./apps/mydata/dist/ s3://mfa-template-s3/mydata --exclude "index.html"
      - aws cloudfront create-invalidation --distribution-id E1RI9WI1EF5TV3 --paths '/*'
artifacts:
  files:
    - "**/*"
  base-directory: ./
  

