version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - npm install -g pnpm
      - pnpm install
  pre_build:
    commands:
      - export TURBO_API=$TURBO_API
      - export TURBO_TEAM=$TURBO_TEAM
      - export TURBO_TOKEN=$TURBO_TOKEN
      - mkdir -p .turbo
      - |
        echo "{
          \"apiurl\": \"$TURBO_API\",
          \"teamslug\": \"$TURBO_TEAM\",
          \"token\": \"$TURBO_TOKEN\"
        }" > .turbo/config.json
      - cat .turbo/config.json
  build:
    commands:
      - set -e 
      - echo "Running turborepo build..."
      - pnpm build
  post_build:
    commands:
      - |
        echo "Running deploy script..."
        chmod +x ./deploy.sh

        sync_to_s3_and_invalidate "apps/_shell" ""
        sync_to_s3_and_invalidate "apps/health" "health"
        sync_to_s3_and_invalidate "apps/insurance" "insurance"
        sync_to_s3_and_invalidate "apps/mydata" "mydata"
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

        echo "Deployment complete!"
artifacts:
  files:
    - "apps/*/dist/**/*"
  base-directory: ./
cache:
  paths:
    - '.pnpm-store/**/*'
    - '.turbo/**/*'
